### ISSUE TITLE
duplicating the folder name in the path

### ISSUE THREAD

**Issue by giuliohome** [LambdaFactory/Tennis#3]
I'm getting a bug when I run the tool on windows with the command `%USERPROFILE%\.dotnet\tools\tennis`

![image](https://user-images.githubusercontent.com/3272563/42420047-318b2bb8-82c0-11e8-9007-e106ecbe71ff.png)

Notice that the link is formed with the root folder "vs" repeated two times.

**Comment by giuliohome** [comment]
I guess the problem is in the `fileList` function of the `Layout` module: the running directory is the initial one from which the server has been started while - I suspect - the `href` should be relative to something like the parent directory (to which the current url of the browser is already pointing)...

**Comment by Krzysztof-Cieslak** [comment]
Why not run tool with just `tennis`? Global tools are automatically added to PATH

**Comment by giuliohome** [comment]
ok, I can do that, thank you, but the issue doesn't disappear...

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #3
